$schema: ../../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: info
  show_progress: true
  path: "logs/instagram_gift_advisor.jsonl"
  path_settings:
    path_pattern: "logs/instagram_gift_advisor_{unique_id}.jsonl"
    unique_id: "timestamp"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    apify:
      command: "npx"
      args:
        [
          "mcp-remote",
          "https://mcp.apify.com/sse?actors=apify/instagram-api-scraper",
          "--header",
          "Authorization: Bearer ${APIFY_API_TOKEN}",
        ]
    brave-search:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-brave-search"]
      env:
        BRAVE_API_KEY: "${BRAVE_API_KEY}"

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: "gpt-4o-mini"
anthropic:
  default_model: claude-sonnet-4-20250514
